# Gradle
org.gradle.jvmargs=-Xmx8048M -Dkotlin.daemon.jvm.options\="-Xmx8048M" -Djava.net.preferIPv4Stack=true
org.gradle.parallel=true
org.gradle.caching=true
systemProp.path=/usr/local/bin:/usr/bin:/bin
# Kotlin
kotlin.code.style=official
#kotlin.js.compiler=ir
# native
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.native.enabled=true
kotlin.incremental=false
systemProp.java.net.preferIPv4Stack=true
# Android
android.useAndroidX=true
android.nonTransitiveRClass=true



# Compose
org.jetbrains.compose.experimental.uikit.enabled=true
org.jetbrains.compose.experimental.jscanvas.enabled=true

# cmake arguments
cmake.assemble.library=true

# custom gradle properties
ai.use.externalToolchain=true
ai.install.model.jump=true