import com.google.protobuf.gradle.GenerateProtoTask
import com.google.protobuf.gradle.id

plugins {
    `java-library`
    kotlin("jvm")
    alias(libs.plugins.protobuf)
}

val serviceGen = project(projects.shared.generator.serviceGen.path)

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    // 确保在protobuf生成任务执行前，serviceGen的jar已经构建完成
    tasks.withType<GenerateProtoTask>().configureEach {
        dependsOn("${serviceGen.path}:jar")
    }
    sourceSets["main"].apply {
        kotlin.setSrcDirs(listOf("src/main/java"))
    }
}
kotlin{
    jvmToolchain {
        this.languageVersion.set(JavaLanguageVersion.of(17))
        this.vendor.set(JvmVendorSpec.ADOPTIUM)
    }
    sourceSets["main"].apply {
        kotlin.exclude("**/com/airobot/protocol/pb/**")
        kotlin.setSrcDirs(listOf("src/main/kotlin"))
    }
}

dependencies {
    // This is needed for includes, ref: https://github.com/google/protobuf-gradle-plugin/issues/41#issuecomment-143884188
    compileOnly(libs.google.protobuf.java)
}

protobuf {
    protoc {
        artifact = libs.google.protoc.get().toString()
    }
    plugins {
        id("airobot") {
            artifact = libs.pbandk.gen.get().toString()
        }
    }
    generateProtoTasks {
        ofSourceSet("main").forEach { task ->
            task.builtins {
                this.remove(GenerateProtoTask.PluginOptions("java"))

            }
            task.plugins {
                id("airobot") {
                    // Publish the code generated by pbandk as part of the `:protobuf-codegen` project's
                    // `commonMain` source set. This allows other Kotlin Multiplatform sub-projects to consume the
                    // pbandk-generated Kotlin code using a regular gradle project dependency.
                    val outputDir = task.getOutputDir(this)
                    /*project.kotlin.sourceSets.commonMain.configure {
                        // `builtBy` ensures that gradle will automatically run the `generateProto` task before trying
                        // to compile the generated Kotlin code
                        println("outputDir::${outputDir}")
                        kotlin.srcDir(project.files(outputDir).builtBy(this@apply))
                    }*/
                    option("log=debug")
                    option("kotlin_package=com.airobot.protocol.pb")


                    option("kotlin_service_gen=${serviceGen.layout.
                    buildDirectory.get()
                    }/libs/${projects.shared.generator.serviceGen.name}.jar|com.airobot.protocol.Generator")

                    task.doLast {
                        // 复制生成的proto文件到src/main/kotlin/目录
                        val outputDir = task.getOutputDir(this@id)
                        val source = File(outputDir)
                        val path = source.relativeTo(projectDir)
                        val dest = projectDir.resolve("src/main/source/")
                        dest.deleteRecursively()
                        source.copyRecursively(dest, overwrite = true)
                    }
                }
            }
        }
    }
}